cd "G:\Mi unidad\1. PROYECTOS TELLO 2022\SCM SPILL OVERS\intermedios\delincuencia"
import excel delincuencia.xlsx, firstrow clear
rename NombreProvincia provincia

gen prov=1 if provincia=="ABANCAY"
	replace prov=2 if provincia=="ACOBAMBA"
	replace prov=3 if provincia=="ACOMAYO"
	replace prov=4 if provincia=="ALTO AMAZONAS"
	replace prov=5 if provincia=="AMBO"
	replace prov=6 if provincia=="ANDAHUAYLAS"
	replace prov=7 if provincia=="ANGARAES"
	replace prov=8 if provincia=="ANTA"
	replace prov=9 if provincia=="ANTONIO RAIMONDI"
	replace prov=10 if provincia=="AREQUIPA"
	replace prov=11 if provincia=="ASCOPE"
	replace prov=12 if provincia=="ATALAYA"
	replace prov=13 if provincia=="AYABACA"
	replace prov=14 if provincia=="AYMARAES"
	replace prov=15 if provincia=="AZANGARO"
	replace prov=16 if provincia=="BAGUA"
	replace prov=17 if provincia=="BARRANCA"
	replace prov=18 if provincia=="BELLAVISTA"
	replace prov=19 if provincia=="BOLIVAR"
	replace prov=20 if provincia=="BOLOGNESI"
	replace prov=21 if provincia=="BONGARA"
	replace prov=22 if provincia=="CAJABAMBA"
	replace prov=23 if provincia=="CAJAMARCA"
	replace prov=24 if provincia=="CAJATAMBO"
	replace prov=25 if provincia=="CALCA"
	replace prov=26 if provincia=="CALLAO"
	replace prov=27 if provincia=="CAMANA"
	replace prov=28 if provincia=="CANCHIS"
	replace prov=29 if provincia=="CANDARAVE"
	replace prov=30 if provincia=="CANGALLO"
	replace prov=31 if provincia=="CARABAYA"
	replace prov=32 if provincia=="CARAVELI"
	replace prov=33 if provincia=="CARHUAZ"
	replace prov=34 if provincia=="CARLOS FERMIN FITZCARRALD"
	replace prov=35 if provincia=="CASMA"
	replace prov=36 if provincia=="CASTILLA"
	replace prov=37 if provincia=="CASTROVIRREYNA"
	replace prov=38 if provincia=="CAYLLOMA"
	replace prov=39 if provincia=="CAÑETE"
	replace prov=40 if provincia=="CELENDIN"
	replace prov=41 if provincia=="CHACHAPOYAS"
	replace prov=42 if provincia=="CHANCHAMAYO"
	replace prov=43 if provincia=="CHEPEN"
	replace prov=44 if provincia=="CHICLAYO"
	replace prov=45 if provincia=="CHINCHA"
	replace prov=46 if provincia=="CHINCHEROS"
	replace prov=47 if provincia=="CHOTA"
	replace prov=48 if provincia=="CHUCUITO"
	replace prov=49 if provincia=="CHUMBIVILCAS"
	replace prov=50 if provincia=="CONCEPCION"
	replace prov=51 if provincia=="CONDESUYOS"
	replace prov=52 if provincia=="CONDORCANQUI"
	replace prov=53 if provincia=="CONTRALMIRANTE VILLAR"
	replace prov=54 if provincia=="CONTUMAZA"
	replace prov=55 if provincia=="CORONEL PORTILLO"
	replace prov=56 if provincia=="COTABAMBAS"
	replace prov=57 if provincia=="CUSCO"
	replace prov=58 if provincia=="CUTERVO"
	replace prov=59 if provincia=="DANIEL ALCIDES CARRION"
	replace prov=60 if provincia=="DATEM DEL MARAÑON"
	replace prov=61 if provincia=="DOS DE MAYO"
	replace prov=62 if provincia=="EL COLLAO"
	replace prov=63 if provincia=="EL DORADO"
	replace prov=64 if provincia=="ESPINAR"
	replace prov=65 if provincia=="FERREÑAFE"
	replace prov=66 if provincia=="GENERAL SANCHEZ CERRO"
	replace prov=67 if provincia=="GRAN CHIMU"
	replace prov=68 if provincia=="GRAU"
	replace prov=69 if provincia=="HUALGAYOC"
	replace prov=70 if provincia=="HUAMALIES"
	replace prov=71 if provincia=="HUAMANGA"
	replace prov=72 if provincia=="HUANCA SANCOS"
	replace prov=73 if provincia=="HUANCABAMBA"
	replace prov=74 if provincia=="HUANCANE"
	replace prov=75 if provincia=="HUANCAVELICA"
	replace prov=76 if provincia=="HUANCAYO"
	replace prov=77 if provincia=="HUANTA"
	replace prov=78 if provincia=="HUANUCO"
	replace prov=79 if provincia=="HUARAL"
	replace prov=80 if provincia=="HUARAZ"
	replace prov=81 if provincia=="HUARI"
	replace prov=82 if provincia=="HUARMEY"
	replace prov=83 if provincia=="HUAROCHIRI"
	replace prov=84 if provincia=="HUAURA"
	replace prov=85 if provincia=="HUAYTARA"
	replace prov=86 if provincia=="ICA"
	replace prov=87 if provincia=="ILO"
	replace prov=88 if provincia=="ISLAY"
	replace prov=89 if provincia=="JAEN"
	replace prov=90 if provincia=="JAUJA"
	replace prov=91 if provincia=="JORGE BASADRE"
	replace prov=92 if provincia=="LA CONVENCION"
	replace prov=93 if provincia=="LA MAR"
	replace prov=94 if provincia=="LA UNION"
	replace prov=95 if provincia=="LAMAS"
	replace prov=96 if provincia=="LAMBAYEQUE"
	replace prov=97 if provincia=="LAMPA"
	replace prov=98 if provincia=="LAURICOCHA"
	replace prov=99 if provincia=="LEONCIO PRADO"
	replace prov=100 if provincia=="LIMA"
	replace prov=101 if provincia=="LORETO"
	replace prov=102 if provincia=="LUCANAS"
	replace prov=103 if provincia=="LUYA"
	replace prov=104 if provincia=="MANU"
	replace prov=105 if provincia=="MARISCAL CACERES"
	replace prov=106 if provincia=="MARISCAL NIETO"
	replace prov=107 if provincia=="MARISCAL RAMON CASTILLA"
	replace prov=108 if provincia=="MAYNAS"
	replace prov=109 if provincia=="MELGAR"
	replace prov=110 if provincia=="MOHO"
	replace prov=111 if provincia=="MORROPON"
	replace prov=112 if provincia=="MOYOBAMBA"
	replace prov=113 if provincia=="NAZCA"
	replace prov=114 if provincia=="OTUZCO"
	replace prov=115 if provincia=="OXAPAMPA"
	replace prov=116 if provincia=="OYON"
	replace prov=117 if provincia=="PACASMAYO"
	replace prov=118 if provincia=="PACHITEA"
	replace prov=119 if provincia=="PADRE ABAD"
	replace prov=120 if provincia=="PAITA"
	replace prov=121 if provincia=="PALLASCA"
	replace prov=122 if provincia=="PALPA"
	replace prov=123 if provincia=="PARINACOCHAS"
	replace prov=124 if provincia=="PARURO"
	replace prov=125 if provincia=="PASCO"
	replace prov=126 if provincia=="PATAZ"
	replace prov=127 if provincia=="PAUCARTAMBO"
	replace prov=128 if provincia=="PICOTA"
	replace prov=129 if provincia=="PISCO"
	replace prov=130 if provincia=="PIURA"
	replace prov=131 if provincia=="POMABAMBA"
	replace prov=132 if provincia=="PUERTO INCA"
	replace prov=133 if provincia=="PUNO"
	replace prov=134 if provincia=="QUISPICANCHI"
	replace prov=135 if provincia=="REQUENA"
	replace prov=136 if provincia=="RIOJA"
	replace prov=137 if provincia=="RODRIGUEZ DE MENDOZA"
	replace prov=138 if provincia=="SAN ANTONIO DE PUTINA"
	replace prov=139 if provincia=="SAN IGNACIO"
	replace prov=140 if provincia=="SAN MARTIN"
	replace prov=141 if provincia=="SAN ROMAN"
	replace prov=142 if provincia=="SANCHEZ CARRION"
	replace prov=143 if provincia=="SANDIA"
	replace prov=144 if provincia=="SANTA"
	replace prov=145 if provincia=="SANTA CRUZ"
	replace prov=146 if provincia=="SANTIAGO DE CHUCO"
	replace prov=147 if provincia=="SATIPO"
	replace prov=148 if provincia=="SECHURA"
	replace prov=149 if provincia=="SULLANA"
	replace prov=150 if provincia=="TACNA"
	replace prov=151 if provincia=="TAHUAMANU"
	replace prov=152 if provincia=="TALARA"
	replace prov=153 if provincia=="TAMBOPATA"
	replace prov=154 if provincia=="TARATA"
	replace prov=155 if provincia=="TARMA"
	replace prov=156 if provincia=="TAYACAJA"
	replace prov=157 if provincia=="TOCACHE"
	replace prov=158 if provincia=="TRUJILLO"
	replace prov=159 if provincia=="TUMBES"
	replace prov=160 if provincia=="UCAYALI"
	replace prov=161 if provincia=="URUBAMBA"
	replace prov=162 if provincia=="UTCUBAMBA"
	replace prov=163 if provincia=="VICTOR FAJARDO"
	replace prov=164 if provincia=="YAROWILCA"
	replace prov=165 if provincia=="YAULI"
	replace prov=166 if provincia=="YAUYOS"
	replace prov=167 if provincia=="YUNGAY"
	replace prov=168 if provincia=="YUNGUYO"
	replace prov=169 if provincia=="ZARUMILLA"
	replace prov=170 if provincia=="ANTABAMBA"
	replace prov=171 if provincia=="ASUNCION"
	replace prov=172 if provincia=="CHUPACA"
	replace prov=173 if provincia=="CHURCAMPA"
	replace prov=174 if provincia=="HUACAYBAMBA"
	replace prov=175 if provincia=="HUALLAGA"
	replace prov=176 if provincia=="HUAYLAS"
	replace prov=177 if provincia=="JUNIN"
	replace prov=178 if provincia=="MARAÑON"
	replace prov=179 if provincia=="OCROS"
	replace prov=180 if provincia=="PAUCAR DEL SARA SARA"
	replace prov=181 if provincia=="PURUS"
	replace prov=182 if provincia=="RECUAY"
	replace prov=183 if provincia=="SAN MARCOS"
	replace prov=184 if provincia=="SIHUAS"
	replace prov=185 if provincia=="VILCAS HUAMAN"
	replace prov=186 if provincia=="VIRU"
	replace prov=187 if provincia=="CANAS"
	replace prov=188 if provincia=="CANTA"
	replace prov=189 if provincia=="JULCAN"
	replace prov=190 if provincia=="SAN MIGUEL"
	replace prov=191 if provincia=="SUCRE"
	replace prov=192 if provincia=="MARISCAL LUZURIAGA"
	replace prov=193 if provincia=="SAN PABLO"
	replace prov=194 if provincia=="AIJA"
	replace prov=195 if provincia=="CORONGO"
	rename provincia Nombreprovincia
sort prov
drop if missing(prov)
rename prov provincia
egen max_indicedecriminalidad=max(indicedecriminalidad)
save delincuencia.dta, replace
